name: "Request PR Review"
description: "Request pull request review to reviewers periodically"
inputs:
  token:
    description: "github token"
    required: true
  slackIds:
    description: "GitHub repo variable that match github nickname to slack nickname"
    required: true
  slackBotToken:
    description: "slack bot token for messaging"
    required: true
  repoUrl:
    description: "repository url where action runs"
    required: true
runs:
  using: node12
  main: index.js
